// Copyright (C) 2025 zk4x
// SPDX-License-Identifier: LGPL-3.0-only
//
// Auto-generated by regression.py. 167 features, Ridge.
#![allow(unused)]
use super::cost::Cost;
impl Cost {
    pub fn predict_time_us(
        num_groups: u32, wi_per_group: u32, wi_ops: u32,
        wi_compute_ops: u32, wi_barriers: u32,
        wi_global_load_bits: u32, wi_global_store_bits: u32,
        wi_local_load_bits: u32, wi_local_store_bits: u32,
        wi_peak_reg_bytes: u32, wi_branches: u32,
        wi_global_load_lidx_stride: u32, wi_global_store_lidx_stride: u32,
        wi_local_load_lidx_stride: u32, wi_local_store_lidx_stride: u32,
        warp_size: u32, max_local_threads: u32, max_register_bytes: u32,
        wi_register_load_bits: u32, wi_register_store_bits: u32,
        gws0: u32, gws1: u32, gws2: u32,
        lws0: u32, lws1: u32, lws2: u32,
        max_loop_depth: u32,
        preferred_vector_size: u32, local_mem_size: u32,
    ) -> f64 {
        let num_groups = num_groups as f64;
        let wi_per_group = wi_per_group as f64;
        let wi_ops = wi_ops as f64;
        let wi_compute_ops = wi_compute_ops as f64;
        let wi_barriers = wi_barriers as f64;
        let wi_global_load_bits = wi_global_load_bits as f64;
        let wi_global_store_bits = wi_global_store_bits as f64;
        let wi_local_load_bits = wi_local_load_bits as f64;
        let wi_local_store_bits = wi_local_store_bits as f64;
        let wi_peak_reg_bytes = wi_peak_reg_bytes as f64;
        let wi_branches = wi_branches as f64;
        let wi_global_load_lidx_stride = wi_global_load_lidx_stride as f64;
        let wi_global_store_lidx_stride = wi_global_store_lidx_stride as f64;
        let wi_local_load_lidx_stride = wi_local_load_lidx_stride as f64;
        let wi_local_store_lidx_stride = wi_local_store_lidx_stride as f64;
        let warp_size = warp_size as f64;
        let max_local_threads = max_local_threads as f64;
        let max_register_bytes = max_register_bytes as f64;
        let wi_register_load_bits = wi_register_load_bits as f64;
        let wi_register_store_bits = wi_register_store_bits as f64;
        let gws0 = gws0 as f64;
        let gws1 = gws1 as f64;
        let gws2 = gws2 as f64;
        let lws0 = lws0 as f64;
        let lws1 = lws1 as f64;
        let lws2 = lws2 as f64;
        let max_loop_depth = max_loop_depth as f64;
        let preferred_vector_size = preferred_vector_size as f64;
        let local_mem_size = local_mem_size as f64;
        let lng = num_groups.ln();
        let lwpg = (wi_per_group + 1.0).ln();
        let lops = wi_ops.ln();
        let lcop = wi_compute_ops.ln();
        let lgmem = (wi_global_load_bits + wi_global_store_bits + 1.0).ln();
        let ci = wi_compute_ops / (wi_global_load_bits + wi_global_store_bits).max(1.0);
        let barr = wi_barriers;
        let wr = wi_per_group / warp_size.max(1.0);
        let rr = wi_peak_reg_bytes / max_register_bytes.max(1.0);
        let is_comp_bound = if ci > 0.2 { 1.0 } else { 0.0 };
        let is_mem_bound = if ci <= 0.2 { 1.0 } else { 0.0 };

        let features: [f64; 167] = [
            lng,
            lwpg,
            lops,
            lcop,
            lgmem,
            barr,
            wr,
            rr,
            num_groups * wi_per_group,
            wi_ops / wi_compute_ops.max(1.0),
            ci,
            (wi_compute_ops / (wi_global_load_bits + wi_global_store_bits).max(1.0)).ln_1p(),
            (wi_ops / wi_compute_ops.max(1.0)).ln_1p(),
            ((wi_global_load_bits + wi_global_store_bits) / (num_groups * wi_per_group).max(1.0)).ln_1p(),
            ((wi_local_load_bits + wi_local_store_bits + 1.0) / (wi_global_load_bits + wi_global_store_bits + 1.0).max(1.0)).ln_1p(),
            (wi_ops + 100.0).ln(),
            (wi_ops + 10.0).ln(),
            (wi_compute_ops + 100.0).ln(),
            (1000.0 / wi_ops.max(1.0)).ln_1p(),
            (100.0 / wi_ops.max(1.0)).ln_1p(),
            (1000.0 / wi_compute_ops.max(1.0)).ln_1p(),
            wi_ops / (num_groups * wi_per_group).max(1.0),
            wi_compute_ops / (num_groups * wi_per_group).max(1.0),
            wi_ops / num_groups.max(1.0),
            lwpg.max(1e-8).ln(),
            num_groups,
            num_groups * wi_per_group,
            wi_branches.ln_1p(),
            barr * wi_branches.ln_1p(),
            lwpg * wi_branches.ln_1p(),
            lng * lwpg,
            lwpg * lops,
            (wi_ops / num_groups.max(1.0) + 1.0).ln(),
            (wi_ops / (num_groups * wi_per_group).max(1.0)).ln_1p(),
            1.0 / (num_groups * wi_per_group).max(1.0),
            (1.0 / (num_groups * wi_per_group).max(1.0)).ln_1p(),
            (wi_ops / (num_groups * wi_per_group * wi_barriers.max(1.0)).max(1.0)).ln_1p(),
            (wi_per_group * wi_barriers).ln_1p(),
            (if wi_barriers == 0.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 3.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 4.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 5.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 6.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 7.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 8.0 { 1.0 } else { 0.0 }),
            if wi_barriers == 0.0 { 1.0 } else { 0.0 },
            if wi_barriers >= 3.0 && wi_barriers <= 5.0 { 1.0 } else { 0.0 },
            if wi_barriers >= 6.0 { 1.0 } else { 0.0 },
            if wi_barriers > 0.0 { 1.0 } else { 0.0 },
            (if wi_barriers == 0.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 0.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 0.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 3.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 3.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 3.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 4.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 4.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 4.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 5.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 5.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 5.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 6.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 6.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 6.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 7.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 7.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 7.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 8.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 8.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 8.0 { 1.0 } else { 0.0 }) * lops,
            barr * lops,
            barr * lcop,
            barr * lgmem,
            barr * lwpg,
            barr * lng,
            barr * wr,
            wi_global_load_lidx_stride.ln_1p(),
            wi_global_store_lidx_stride.ln_1p(),
            wi_global_load_lidx_stride.ln_1p() * lops,
            wi_global_load_lidx_stride.ln_1p() * lcop,
            wi_global_load_lidx_stride.ln_1p() * lgmem,
            lops * lgmem,
            lcop * lgmem,
            lng * lgmem,
            lwpg * lgmem,
            lops * ci,
            lcop * ci,
            lng * ci,
            lng * wr,
            lwpg * wr,
            lng * rr,
            lwpg * rr,
            lng * lcop,
            lwpg * lops,
            wr,
            (32.0 / wi_per_group.max(1.0)).ln(),
            lng * (32.0 / wi_per_group.max(1.0)).ln(),
            lwpg * (32.0 / wi_per_group.max(1.0)).ln(),
            1.0 - (wi_global_load_lidx_stride / 32.0).min(1.0),
            1.0 - (wi_global_store_lidx_stride / 32.0).min(1.0),
            barr / (wi_per_group + 1.0).log2().max(1.0),
            wi_compute_ops / num_groups.max(1.0),
            (32.0 / wi_per_group.max(1.0)).max(1e-8).ln(),
            ((num_groups * wi_per_group) / 2048.0).min(1.0),
            if wi_barriers > 0.0 { (wi_barriers + 1.0).log2() } else { 0.0 },
            barr * (wi_local_load_bits + wi_local_store_bits).ln_1p(),
            wi_compute_ops / (num_groups * wi_per_group).max(1.0),
            (wi_local_load_bits + wi_local_store_bits) / 65536.0,
            wr,
            (32.0 - wi_per_group) / 32.0,
            wi_compute_ops / (num_groups * wi_barriers.max(1.0)).max(1.0),
            barr * (barr).ln_1p() / (wi_ops).ln_1p().max(1.0),
            wi_ops / (num_groups * (wi_per_group).ln_1p()).max(1.0),
            wi_ops / wi_barriers.max(1.0),
            barr / (wi_ops).ln_1p().max(1.0),
            barr / (wi_ops).ln_1p().max(1.0),
            ((wi_global_load_bits + wi_global_store_bits) / wi_compute_ops.max(1.0) + 1.0).ln(),
            (lng.abs()).ln_1p(),
            (lwpg.abs()).ln_1p(),
            (lops.abs()).ln_1p(),
            (num_groups / wi_ops.max(1.0) + 1.0).ln(),
            ((num_groups * wi_per_group) / wi_ops.max(1.0) + 1.0).ln(),
            (if wi_barriers >= 3.0 && wi_barriers <= 5.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lgmem,
            wi_compute_ops / (num_groups * wi_per_group).max(1.0),
            (wi_compute_ops + 1.0).ln() * ((num_groups * wi_per_group) + 1.0).ln(),
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lcop,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lgmem,
            wi_register_load_bits.ln_1p(),
            wi_register_store_bits.ln_1p(),
            wi_register_load_bits / (wi_global_load_bits + wi_global_store_bits).max(1.0),
            gws0.ln_1p(),
            gws1.ln_1p(),
            gws2.ln_1p(),
            lws0.ln_1p(),
            lws1.ln_1p(),
            lws2.ln_1p(),
            lws0 / wi_per_group.max(1.0),
            lws1 / wi_per_group.max(1.0),
            lws2 / wi_per_group.max(1.0),
            lws0 * lws1,
            gws0 / num_groups.max(1.0),
            gws1 / num_groups.max(1.0),
            max_loop_depth,
            max_loop_depth * lops,
            max_loop_depth * barr,
            local_mem_size.ln_1p(),
            preferred_vector_size,
            ci,
            is_comp_bound,
            is_mem_bound,
            is_comp_bound * lgmem,
            is_comp_bound * lops,
            is_comp_bound * lcop,
            is_comp_bound * lng,
            is_comp_bound * lwpg,
            is_comp_bound * barr,
            is_mem_bound * lgmem,
            is_mem_bound * lops,
            is_mem_bound * lcop,
            is_mem_bound * lng,
            is_mem_bound * lwpg,
            is_mem_bound * barr,
        ];

        const SM: &[f64] = &[
            7.15793760e+00, 2.14564487e+00, 9.64859344e+00, 9.32425481e+00, 1.12520003e+01, 3.01453237e-01, 1.17459632e+00, 1.90104762e+00,
            3.20598629e+06, 1.40502764e+00, 1.66010276e-01, 1.50061691e-01, 8.72000671e-01, 3.57936835e+00, 1.61430014e-02, 9.77270604e+00,
            9.67100457e+00, 9.48811998e+00, 4.24578279e-01, 1.24112602e-01, 5.14492549e-01, 1.21865422e+06, 8.37790661e+05, 1.22124636e+06,
            4.90562675e-01, 1.96700766e+05, 3.20598629e+06, 1.07666886e-01, 5.46229014e-01, 3.73768289e-01, 1.42926318e+01, 1.94420841e+01,
            3.62832291e+00, 2.56095090e+00, 1.49798201e-02, 1.23955918e-02, 2.53017790e+00, 3.03281871e-01, 9.38261455e-01, 9.21486765e-03,
            2.11952634e-02, 1.25997032e-02, 9.11876822e-03, 5.56308928e-03, 4.04685381e-03, 9.38261455e-01, 4.30098342e-02, 1.87287113e-02,
            6.17385455e-02, 6.71941956e+00, 1.93554743e+00, 9.20151461e+00, 6.99720884e-02, 2.32419234e-02, 6.99342580e-02, 1.88655081e-01,
            7.03255375e-02, 1.47343920e-01, 6.99097827e-02, 4.17566921e-02, 9.87633154e-02, 4.31197058e-02, 3.18838420e-02, 6.83974365e-02,
            3.84090886e-02, 2.32224891e-02, 3.66458003e-02, 2.84522887e-02, 1.96669504e-02, 2.59941021e-02, 2.16785307e+00, 2.01728230e+00,
            2.54463337e+00, 1.07100746e+00, 2.06928567e+00, 4.49457038e-01, 1.86875074e+00, 1.26670667e+00, 1.87414972e+01, 1.81489135e+01,
            2.18477150e+01, 1.15680975e+02, 1.12241115e+02, 7.83796193e+01, 2.28158845e+01, 1.69461825e+00, 1.65016169e+00, 1.22453721e+00,
            7.58830061e+00, 6.11903991e+00, 1.23926932e+01, 3.49351077e+00, 6.47594264e+01, 1.94420841e+01, 1.17459632e+00, 1.64430856e+00,
            1.30725113e+01, 7.47836874e-01, 7.73682904e-01, 8.73617903e-01, 6.25221843e-02, 8.39765863e+05, 1.64430856e+00, 7.17824131e-01,
            1.55330483e-01, 1.88131316e+00, 8.37790661e+05, 4.69204220e-04, 1.17459632e+00, -1.74596316e-01, 8.39668339e+05, 8.01373618e-02,
            1.22015987e+06, 1.44224228e+06, 4.40442903e-02, 4.40442903e-02, 2.07729570e+00, 1.96353363e+00, 1.03292371e+00, 2.32529485e+00,
            1.13766706e+00, 1.89172239e+00, 3.16041494e-01, 4.47078833e-01, 5.25460175e-01, 8.37790661e+05, 8.04237054e+01, 4.38518036e-01,
            2.10097434e-01, 4.47078833e-01, 4.16246936e-01, 5.25460175e-01, 9.82196580e+00, 9.82196580e+00, 4.94035880e-01, 3.77097669e+00,
            3.38528245e+00, 9.74465239e-01, 1.46498209e+00, 1.19559418e+00, 8.11569956e-01, 7.24821730e-01, 6.00224856e-01, 4.71583286e-01,
            2.92994779e+01, 2.79507163e-01, 1.25759357e-01, 1.25421503e+00, 1.29690353e+01, 4.26425208e-01, 1.08026932e+01, 1.60000000e+01,
            1.66010276e-01, 1.74356401e-01, 8.25643599e-01, 2.15694502e+00, 1.98287512e+00, 1.95483420e+00, 1.45161819e+00, 3.83955623e-01,
            9.41987977e-02, 9.09505530e+00, 7.66571832e+00, 7.36942061e+00, 5.70631941e+00, 1.76168924e+00, 2.07254439e-01,
        ];
        const SC: &[f64] = &[
            3.63002713e+00, 1.54498877e+00, 2.70086682e+00, 2.78964259e+00, 2.66411868e+00, 1.22720912e+00, 3.46566003e+00, 2.30315390e+00,
            4.94640872e+07, 2.64632766e-01, 1.05530948e-01, 8.11085362e-02, 1.03438484e-01, 3.50396082e+00, 1.05135288e-01, 2.46271113e+00,
            2.65243623e+00, 2.48539601e+00, 8.98417099e-01, 3.62168687e-01, 1.03475143e+00, 3.37493812e+07, 2.18302146e+07, 3.37492994e+07,
            7.53699146e-01, 1.91307905e+06, 4.94640872e+07, 4.23781213e-01, 2.32869841e+00, 1.54646199e+00, 1.29512432e+01, 1.42987183e+01,
            3.42740416e+00, 2.99038333e+00, 8.85009701e-02, 6.33232076e-02, 2.97808481e+00, 1.21121473e+00, 2.40680073e-01, 9.55507921e-02,
            1.44034802e-01, 1.11539009e-01, 9.50558588e-02, 7.43783659e-02, 6.34860361e-02, 2.40680073e-01, 2.02879246e-01, 1.35565286e-01,
            2.40680073e-01, 3.79957994e+00, 1.57675838e+00, 3.50954561e+00, 8.58278023e-01, 2.42924714e-01, 7.41565805e-01, 1.47721870e+00,
            4.91957507e-01, 1.02129428e+00, 8.41766358e-01, 3.82109693e-01, 9.01530596e-01, 6.72862742e-01, 3.32363529e-01, 7.30904534e-01,
            6.31125260e-01, 3.10484104e-01, 4.99195111e-01, 5.45703363e-01, 3.08530226e-01, 4.16013255e-01, 8.98269732e+00, 8.39424550e+00,
            1.05019869e+01, 4.68129889e+00, 1.05251487e+01, 2.68450103e+00, 2.23955949e+00, 1.59535416e+00, 2.32381993e+01, 2.24548826e+01,
            2.69707114e+01, 5.28376542e+01, 5.28756400e+01, 4.37591179e+01, 1.63130694e+01, 1.52262126e+00, 1.52566881e+00, 1.05248012e+00,
            2.48565143e+01, 2.25870448e+01, 1.48959106e+01, 5.30416288e+00, 3.89034462e+01, 1.42987183e+01, 3.46566003e+00, 1.80591672e+00,
            1.64509423e+01, 4.35747089e+00, 3.38464687e-01, 2.41490854e-01, 2.50178663e-01, 2.18301532e+07, 1.80591672e+00, 4.09975317e-01,
            6.11387054e-01, 7.73455746e+00, 2.18302146e+07, 1.87974769e-03, 3.46566003e+00, 3.46566003e+00, 2.18301569e+07, 3.55636532e-01,
            3.37493327e+07, 3.38102480e+07, 1.85620894e-01, 1.85620894e-01, 4.03479988e-01, 5.83858163e-01, 4.69960673e-01, 3.02905104e-01,
            2.18534580e+00, 3.12733152e+00, 1.53042225e+00, 1.79035640e+00, 2.09683835e+00, 2.18302146e+07, 3.86352097e+01, 2.15254793e+00,
            8.45062381e-01, 1.79035640e+00, 1.67517373e+00, 2.09683835e+00, 3.70191063e+00, 3.70191063e+00, 4.87888656e-01, 2.07950087e+00,
            2.20899857e+00, 1.00496967e+00, 1.08614435e+00, 9.39616929e-01, 5.59244732e-01, 4.05902765e-01, 4.37737489e-01, 4.37985457e-01,
            8.97869462e+01, 4.19281168e-01, 2.50786999e-01, 7.68756393e-01, 9.41742940e+00, 1.96406236e+00, 1.00000000e+00, 1.00000000e+00,
            1.05530948e-01, 3.79415664e-01, 3.79415664e-01, 4.83662058e+00, 4.47094727e+00, 4.42361972e+00, 3.34514668e+00, 1.06063479e+00,
            7.21727591e-01, 4.78954049e+00, 4.20780660e+00, 4.12621925e+00, 4.30742206e+00, 1.61705446e+00, 1.01202655e+00,
        ];
        const RC: &[f64] = &[
            3.23234867e-01, -1.56937558e+00, 3.81366657e+00, -3.51517935e+01, 2.87327018e+01, -2.46042728e-02, 3.59108845e-01, 1.23194858e-01,
            1.36758127e-03, 2.06174005e-01, 3.29982665e-01, 2.63278343e-01, -8.19445172e-01, -1.71237548e-01, 2.67893852e-02, 4.04892769e+00,
            -2.88719265e+00, 9.30813080e-01, -4.02006647e-01, -9.08082576e-01, 2.81848485e-01, -1.92543788e+00, -3.04142242e+00, -1.19950144e+01,
            -2.23774298e+00, -6.09916930e-03, 1.36789528e-03, -3.28511079e-02, -1.74857937e-02, -1.12796271e-01, 7.57005302e-01, 4.44087900e-01,
            1.91622636e+00, -7.90212373e-02, -1.64941782e-01, 2.11367063e-01, 4.30562468e-01, -1.04892490e-01, 3.92977568e-02, -3.71968202e-02,
            -3.88035423e-02, -6.99590986e-03, -1.66399353e-02, 2.15180979e-03, 2.97277584e-02, 3.92979543e-02, -4.89177850e-02, 3.43619440e-03,
            -3.92977144e-02, 2.78217608e-01, -1.46771515e+00, 2.77171851e+00, 2.80188823e-02, -8.69194533e-02, 2.16958481e-01, 4.35512645e-02,
            -1.31780736e-01, 2.02539239e-01, 1.94866055e-02, -7.53755792e-02, 1.00208158e-01, 7.52526696e-03, -1.66427030e-02, 1.34010231e-01,
            7.40896183e-03, 2.15390564e-03, 4.75333834e-02, 3.14487331e-03, 2.97279834e-02, -1.68468218e-02, 2.73801854e-01, 2.70278995e-01,
            1.31663191e-01, -9.01044044e-02, 4.63979383e-02, -3.74652697e-02, -7.90192670e-02, -4.06185768e-02, -1.60562528e+00, 7.87088317e-01,
            8.88443530e-01, 3.13736842e+00, -4.28911933e+00, 3.51087203e-01, -2.81069417e-01, -1.73679123e+00, 1.54334455e+00, 4.54461547e-02,
            -2.78226362e-02, -1.03565900e+00, -8.26805757e-02, -2.10827898e-04, 1.38288472e+00, 4.44088142e-01, 3.59108745e-01, -4.69843673e+00,
            8.91682708e-01, 1.13344616e+00, -3.62160060e-02, -1.38499600e-02, 1.19149219e-01, -1.67929235e+01, -4.69843673e+00, 1.99523914e-03,
            -3.28469568e-02, -3.45999368e-02, -3.04142105e+00, -9.83390774e-02, 3.59108745e-01, -3.59108819e-01, 2.58975792e+01, -3.45540001e-01,
            1.36572174e+01, 2.76340753e-01, 1.50544619e-01, 1.50544619e-01, -5.10417165e+00, -6.76028187e-02, -2.18521625e+00, -2.35688197e+00,
            -1.17106602e+00, -2.80802625e-01, 2.99320834e-01, 3.19904002e-01, 3.40158879e-03, -3.04142105e+00, -1.75161421e+00, 5.39972731e-02,
            -1.30692103e-01, 3.19904004e-01, -2.93363019e-01, 3.40159031e-03, 9.18737445e-03, 9.18737570e-03, 2.63153882e-03, 5.16995963e-01,
            5.50484118e-01, 2.94600324e-01, -4.32541493e-02, -8.78251220e-02, -5.00671507e-02, 3.69982974e-02, 9.08710686e-02, 2.74838850e-02,
            -1.04229839e-02, -2.72691690e-02, -3.29640467e-03, 7.37172422e-03, -2.25996211e-02, -4.02272563e-03, -1.74930243e-26, 0.00000000e+00,
            3.29982627e-01, 3.42709563e-02, -3.42716534e-02, 7.96384920e+00, 1.31325386e+00, -1.19358218e+01, 1.20327491e-01, -7.09480870e-01,
            -8.06897096e-03, 7.94005463e+00, 1.05249711e+00, -1.09692200e+01, 1.78959762e-01, -1.03408671e+00, -2.40804911e-02,
        ];
        let ri: f64 = 5.00000000e-01;

        let mut pred = ri;
        for i in 0..167 {
            pred += RC[i] * (features[i] - SM[i]) / SC[i];
        }
        pred * 1_000_000.0
    }
}
