// Copyright (C) 2025 zk4x
// SPDX-License-Identifier: LGPL-3.0-only
//
// Auto-generated by regression.py. Do not edit manually.
// Ridge features: 20, DT leaves: 80
// Total parameters: 100

use super::cost::Cost;

impl Cost {
    pub fn predict_log_time(
        num_groups: u32, wi_per_group: u32, wi_ops: u32,
        wi_compute_ops: u32, wi_barriers: u32,
        wi_global_load_bits: u32, wi_global_store_bits: u32,
        wi_local_load_bits: u32, wi_local_store_bits: u32,
        wi_peak_reg_bytes: u32, wi_branches: u32,
        wi_global_load_lidx_stride: u32, wi_global_store_lidx_stride: u32,
        wi_local_load_lidx_stride: u32, wi_local_store_lidx_stride: u32,
        warp_size: u32, max_local_threads: u32, max_register_bytes: u32,
    ) -> f32 {
        // Compute transformed features from raw inputs
        let lng = (num_groups as f32).ln();
        let lwpg = (wi_per_group as f32 + 1.0).ln();
        let lops = (wi_ops as f32).ln();
        let lcop = (wi_compute_ops as f32).ln();
        let lgmem = ((wi_global_load_bits + wi_global_store_bits) as f32 + 1.0).ln();
        let log_inv_threads = (1.0 / (num_groups * wi_per_group) as f32).ln_1p();
        let ci = wi_compute_ops as f32 / ((wi_global_load_bits + wi_global_store_bits) as f32).max(1.0);
        let barr = wi_barriers as f32;
        let wr = wi_per_group as f32 / warp_size as f32;
        let rr = wi_peak_reg_bytes as f32 / max_register_bytes.max(1) as f32;

        // Build feature vector for Ridge
        let features: [f32; 20] = [
            lwpg,  // lwpg
            lcop,  // lcop
            lgmem,  // lgmem
            (wi_ops as f32 + 10.0).ln(),  // log_ops_10
            wi_ops as f32 / (num_groups * wi_per_group).max(1) as f32,  // ops_per_thread
            wi_ops as f32 / num_groups.max(1) as f32,  // ops_per_group
            lwpg.max(1e-8).ln(),  // log_lwpg
            (wi_ops as f32 / (num_groups * wi_per_group).max(1) as f32).ln_1p(),  // log_opt
            (if wi_barriers == 0 { 1.0 } else { 0.0 }) * lwpg,  // b0*lwpg
            lops * lgmem,  // lops*lgmem
            lcop * lgmem,  // lcop*lgmem
            (32.0 / wi_per_group.max(1) as f32).ln(),  // log_warp_waste
            (if wi_barriers == 0 { 1.0 } else { 0.0 }) * lcop,  // b0*lcop
            (if wi_barriers == 0 { 1.0 } else { 0.0 }) * lgmem,  // b0*lgmem
            wi_compute_ops as f32 / num_groups.max(1) as f32,  // element_ops
            (32.0 / wi_per_group.max(1) as f32).max(1e-8).ln(),  // warp_div
            wi_compute_ops as f32 / (num_groups * wi_barriers.max(1)).max(1) as f32,  // compute_per_barrier
            wi_ops as f32 / (num_groups as f32 * (wi_per_group as f32).ln_1p()).max(1.0),  // group_work_density
            (lwpg.abs()).ln_1p(),  // log1p_lwpg_raw
            ((num_groups * wi_per_group) as f32 / wi_ops.max(1) as f32 + 1.0).ln(),  // log_threads_per_ops
        ];

        // DT leaf bias (inline tree traversal)
        let leaf_bias: f32 = {
if (lcop) < 14.695358276367188f32 {
    if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 85.1065673828125f32 {
        if ((if wi_barriers == 0 { 1.0 } else { 0.0 }) * lgmem) < 13.172722816467285f32 {
            if ((num_groups * wi_per_group) as f32) < 1310720.0f32 {
                if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 61.976762771606445f32 {
                    if (lgmem) < 11.792017936706543f32 {
                        if ((lng.abs()).ln_1p()) < 2.4508472681045532f32 {
                            if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 55.797279357910156f32 {
                                if ((wi_global_load_lidx_stride as f32).ln_1p() * lgmem) < 7.21555757522583f32 {
                                    if (num_groups as f32) < 10240.0f32 {
                                        if ((if wi_barriers == 0 { 1.0 } else { 0.0 }) * lops) < 2.602003335952759f32 {
                                            -0.074346
                                        } else {
                                            if ((num_groups * wi_per_group) as f32) < 14336.0f32 {
                                                -0.088780
                                            } else {
                                                -0.144376
                                            }
                                        }
                                    } else {
                                        -0.101340
                                    }
                                } else {
                                    if (lwpg * rr) < 0.25870873034000397f32 {
                                        -0.165051
                                    } else {
                                        if (rr) < 3.2890625f32 {
                                            -0.144045
                                        } else {
                                            0.016016
                                        }
                                    }
                                }
                            } else {
                                if ((wi_ops as f32 / num_groups.max(1) as f32 + 1.0).ln()) < 0.018744096159934998f32 {
                                    -0.036285
                                } else {
                                    if (((wi_local_load_bits + wi_local_store_bits + 1) as f32 / (wi_global_load_bits + wi_global_store_bits + 1).max(1) as f32).ln_1p()) < 6.0323625802993774e-05f32 {
                                        -0.151389
                                    } else {
                                        if (lcop * ci) < 1.0537550449371338f32 {
                                            -0.085136
                                        } else {
                                            -0.175903
                                        }
                                    }
                                }
                            }
                        } else {
                            if (lng) < 12.130075454711914f32 {
                                -0.050561
                            } else {
                                0.017942
                            }
                        }
                    } else {
                        if (lcop * lgmem) < 134.933349609375f32 {
                            if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 47.645328521728516f32 {
                                -0.078885
                            } else {
                                -0.051698
                            }
                        } else {
                            if (lwpg * lops * (if wi_barriers == 0 { 1.0 } else { 0.0 })) < 25.94330596923828f32 {
                                if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 47.2320671081543f32 {
                                    -0.045386
                                } else {
                                    -0.036414
                                }
                            } else {
                                0.035871
                            }
                        }
                    }
                } else {
                    if (lng * lgmem) < 88.16383743286133f32 {
                        if (lwpg * rr) < 2.953442096710205f32 {
                            if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 74.17771530151367f32 {
                                if (lng * lgmem) < 81.56436157226562f32 {
                                    if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 66.97113418579102f32 {
                                        if ((num_groups as f32 / wi_ops.max(1) as f32).max(1e-8).ln()) < 4.021413087844849f32 {
                                            if (lng * rr) < 5.1606972217559814f32 {
                                                -0.121309
                                            } else {
                                                -0.050887
                                            }
                                        } else {
                                            -0.018188
                                        }
                                    } else {
                                        -0.066139
                                    }
                                } else {
                                    if ((wi_ops as f32 / (num_groups * wi_per_group * wi_barriers.max(1)).max(1) as f32).ln_1p()) < 0.0013761583250015974f32 {
                                        0.007620
                                    } else {
                                        -0.043725
                                    }
                                }
                            } else {
                                if (lops * ci) < 0.6356827020645142f32 {
                                    0.028525
                                } else {
                                    0.017410
                                }
                            }
                        } else {
                            if ((num_groups * wi_per_group) as f32) < 81920.0f32 {
                                if (wi_ops as f32 / (num_groups as f32 * (wi_per_group as f32).ln_1p()).max(1.0)) < 52.39078330993652f32 {
                                    if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 73.7971305847168f32 {
                                        if ((wi_global_load_lidx_stride as f32).ln_1p() * lops) < 5.802663326263428f32 {
                                            -0.037949
                                        } else {
                                            -0.044880
                                        }
                                    } else {
                                        if (lcop * ci) < 0.9567817747592926f32 {
                                            0.031592
                                        } else {
                                            -0.007407
                                        }
                                    }
                                } else {
                                    if (lng * lgmem) < 34.69034004211426f32 {
                                        0.057018
                                    } else {
                                        -0.020239
                                    }
                                }
                            } else {
                                0.025205
                            }
                        }
                    } else {
                        if ((num_groups * wi_per_group) as f32) < 163840.0f32 {
                            if (lng * lgmem) < 95.1612548828125f32 {
                                0.035407
                            } else {
                                0.061593
                            }
                        } else {
                            if ((wi_global_store_lidx_stride as f32).ln_1p()) < 12.300548076629639f32 {
                                0.048910
                            } else {
                                0.047124
                            }
                        }
                    }
                }
            } else {
                if ((if wi_barriers == 0 { 1.0 } else { 0.0 }) * lng) < 14.065676212310791f32 {
                    if ((if wi_barriers == 0 { 1.0 } else { 0.0 }) * lops) < 2.86179256439209f32 {
                        if (lng * lgmem) < 51.40876770019531f32 {
                            -0.023958
                        } else {
                            0.023261
                        }
                    } else {
                        if ((num_groups * wi_per_group) as f32) < 10485760.0f32 {
                            if ((if wi_barriers == 0 { 1.0 } else { 0.0 }) * lgmem) < 5.061251163482666f32 {
                                -0.017564
                            } else {
                                if (lng * lcop) < 57.89606857299805f32 {
                                    0.057151
                                } else {
                                    0.054716
                                }
                            }
                        } else {
                            if (lwpg * lgmem) < 21.910325050354004f32 {
                                0.085754
                            } else {
                                0.067805
                            }
                        }
                    }
                } else {
                    if ((lng.abs()).ln_1p()) < 2.800369381904602f32 {
                        0.146662
                    } else {
                        0.162005
                    }
                }
            }
        } else {
            if (lgmem) < 14.556823253631592f32 {
                if (lgmem) < 14.269405841827393f32 {
                    if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 54.99669075012207f32 {
                        if (lwpg * lops) < 34.877607345581055f32 {
                            if (((wi_ops as f32 / wi_compute_ops.max(1) as f32)).ln_1p()) < 0.8994536101818085f32 {
                                if ((lops.abs()).ln_1p()) < 2.5829657316207886f32 {
                                    -0.011443
                                } else {
                                    0.020342
                                }
                            } else {
                                0.000396
                            }
                        } else {
                            0.061198
                        }
                    } else {
                        0.038345
                    }
                } else {
                    if (((wi_global_load_bits + wi_global_store_bits) as f32 / (num_groups * wi_per_group).max(1) as f32).ln_1p()) < 11.783761024475098f32 {
                        0.086776
                    } else {
                        0.063608
                    }
                }
            } else {
                if ((if wi_barriers == 0 { 1.0 } else { 0.0 }) * lgmem) < 15.367044925689697f32 {
                    if (((num_groups * wi_per_group) as f32 / wi_ops.max(1) as f32 + 1.0).ln()) < 0.0002032239717664197f32 {
                        0.098785
                    } else {
                        0.048189
                    }
                } else {
                    0.202884
                }
            }
        }
    } else {
        if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 117.90045166015625f32 {
            if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 93.73390197753906f32 {
                if (wi_ops as f32 / (num_groups as f32 * (wi_per_group as f32).ln_1p()).max(1.0)) < 0.006292900303378701f32 {
                    0.144993
                } else {
                    if (lcop * ci) < 1.0582632422447205f32 {
                        if (wi_compute_ops as f32 / (num_groups * wi_barriers.max(1)).max(1) as f32) < 9.1171875f32 {
                            0.096842
                        } else {
                            0.074291
                        }
                    } else {
                        if (rr) < 5.3203125f32 {
                            if (((num_groups * wi_per_group) as f32 / wi_ops.max(1) as f32 + 1.0).ln()) < 4.188023328781128f32 {
                                if (lwpg * lgmem) < 36.19500732421875f32 {
                                    0.090458
                                } else {
                                    0.023463
                                }
                            } else {
                                0.064553
                            }
                        } else {
                            0.075190
                        }
                    }
                }
            } else {
                if (rr) < 2.5390625f32 {
                    if (lng * wr) < 11.783502101898193f32 {
                        if (lng * lgmem) < 123.10322952270508f32 {
                            if ((wi_global_store_lidx_stride as f32).ln_1p()) < 0.3465735912322998f32 {
                                if (lng * lwpg) < 24.301971435546875f32 {
                                    0.034865
                                } else {
                                    0.027156
                                }
                            } else {
                                0.148941
                            }
                        } else {
                            0.113303
                        }
                    } else {
                        if (((wi_global_load_bits + wi_global_store_bits) as f32 / wi_compute_ops.max(1) as f32 + 1.0).ln()) < 1.845485270023346f32 {
                            if ((wi_global_load_lidx_stride as f32).ln_1p() * lcop) < 4.987450122833252f32 {
                                0.031434
                            } else {
                                0.108255
                            }
                        } else {
                            0.033229
                        }
                    }
                } else {
                    if (((wi_global_load_bits + wi_global_store_bits) as f32 / wi_compute_ops.max(1) as f32 + 1.0).ln()) < 1.7169694900512695f32 {
                        0.039469
                    } else {
                        if (wi_ops as f32 / (num_groups as f32 * (wi_per_group as f32).ln_1p()).max(1.0)) < 38.004873275756836f32 {
                            if (lng * rr) < 53.9842529296875f32 {
                                0.091493
                            } else {
                                0.118779
                            }
                        } else {
                            0.137232
                        }
                    }
                }
            }
        } else {
            if (lng * lgmem) < 151.6023406982422f32 {
                if ((wi_compute_ops as f32 + 1.0).ln() * ((num_groups * wi_per_group) as f32 + 1.0).ln()) < 143.82078552246094f32 {
                    0.174557
                } else {
                    0.141810
                }
            } else {
                0.259384
            }
        }
    }
} else {
    if ((100.0 / wi_ops.max(1) as f32).ln_1p()) < 2.8235997362457965e-07f32 {
        0.447938
    } else {
        if (rr) < 9.140625f32 {
            0.374155
        } else {
            0.020267
        }
    }
}
        };

        // Ridge linear combination
        let mut result = 5.711902;
        result += 7.347502 * (features[0] - 1.874660) / 1.409357;  // lwpg
        result += 6.526506 * (features[1] - 8.967356) / 3.008489;  // lcop
        result += -0.820678 * (features[2] - 10.869138) / 2.972298;  // lgmem
        result += -4.120573 * (features[3] - 9.336120) / 2.910874;  // log_ops_10
        result += 55.666790 * (features[4] - 10319074.578351) / 115625148.729873;  // ops_per_thread
        result += -20.484689 * (features[5] - 10326005.526752) / 115624549.637686;  // ops_per_group
        result += 4.946116 * (features[6] - 0.363784) / 0.719127;  // log_lwpg
        result += -0.744973 * (features[7] - 4.031321) / 4.229802;  // log_opt
        result += 0.038572 * (features[8] - 1.617858) / 1.403171;  // b0*lwpg
        result += 11.146633 * (features[9] - 109.929196) / 64.155180;  // lops*lgmem
        result += -10.663594 * (features[10] - 106.338001) / 63.555895;  // lcop*lgmem
        result += 4.409473 * (features[11] - 1.959096) / 1.668457;  // log_warp_waste
        result += -2.289511 * (features[12] - 8.454930) / 3.789928;  // b0*lcop
        result += 1.932845 * (features[13] - 10.231101) / 4.094631;  // b0*lgmem
        result += -61.480865 * (features[14] - 6965901.938373) / 77187228.188687;  // element_ops
        result += 4.409473 * (features[15] - 1.959096) / 1.668457;  // warp_div
        result += 61.628613 * (features[16] - 6965764.613061) / 77187240.546892;  // compute_per_barrier
        result += -35.383334 * (features[17] - 10324799.199875) / 115624654.699099;  // group_work_density
        result += -3.510526 * (features[18] - 0.951341) / 0.443264;  // log1p_lwpg_raw
        result += 1.067402 * (features[19] - 1.510333) / 2.876826;  // log_threads_per_ops
        result += leaf_bias;
        result
    }
}
