// Copyright (C) 2025 zk4x
// SPDX-License-Identifier: LGPL-3.0-only
//
// Auto-generated by regression.py. 152 features, Ridge.
#![allow(unused)]
use super::cost::Cost;
impl Cost {
    pub fn predict_time_us(
        num_groups: u32, wi_per_group: u32, wi_ops: u32,
        wi_compute_ops: u32, wi_barriers: u32,
        wi_global_load_bits: u32, wi_global_store_bits: u32,
        wi_local_load_bits: u32, wi_local_store_bits: u32,
        wi_peak_reg_bytes: u32, wi_branches: u32,
        wi_global_load_lidx_stride: u32, wi_global_store_lidx_stride: u32,
        wi_local_load_lidx_stride: u32, wi_local_store_lidx_stride: u32,
        warp_size: u32, max_local_threads: u32, max_register_bytes: u32,
        wi_register_load_bits: u32, wi_register_store_bits: u32,
        gws0: u32, gws1: u32, gws2: u32,
        lws0: u32, lws1: u32, lws2: u32,
        max_loop_depth: u32,
        preferred_vector_size: u32, local_mem_size: u32,
    ) -> f64 {
        let num_groups = num_groups as f64;
        let wi_per_group = wi_per_group as f64;
        let wi_ops = wi_ops as f64;
        let wi_compute_ops = wi_compute_ops as f64;
        let wi_barriers = wi_barriers as f64;
        let wi_global_load_bits = wi_global_load_bits as f64;
        let wi_global_store_bits = wi_global_store_bits as f64;
        let wi_local_load_bits = wi_local_load_bits as f64;
        let wi_local_store_bits = wi_local_store_bits as f64;
        let wi_peak_reg_bytes = wi_peak_reg_bytes as f64;
        let wi_branches = wi_branches as f64;
        let wi_global_load_lidx_stride = wi_global_load_lidx_stride as f64;
        let wi_global_store_lidx_stride = wi_global_store_lidx_stride as f64;
        let wi_local_load_lidx_stride = wi_local_load_lidx_stride as f64;
        let wi_local_store_lidx_stride = wi_local_store_lidx_stride as f64;
        let warp_size = warp_size as f64;
        let max_local_threads = max_local_threads as f64;
        let max_register_bytes = max_register_bytes as f64;
        let wi_register_load_bits = wi_register_load_bits as f64;
        let wi_register_store_bits = wi_register_store_bits as f64;
        let gws0 = gws0 as f64;
        let gws1 = gws1 as f64;
        let gws2 = gws2 as f64;
        let lws0 = lws0 as f64;
        let lws1 = lws1 as f64;
        let lws2 = lws2 as f64;
        let max_loop_depth = max_loop_depth as f64;
        let preferred_vector_size = preferred_vector_size as f64;
        let local_mem_size = local_mem_size as f64;
        let lng = num_groups.ln();
        let lwpg = (wi_per_group + 1.0).ln();
        let lops = wi_ops.ln();
        let lcop = wi_compute_ops.ln();
        let lgmem = (wi_global_load_bits + wi_global_store_bits + 1.0).ln();
        let ci = wi_compute_ops / (wi_global_load_bits + wi_global_store_bits).max(1.0);
        let barr = wi_barriers;
        let wr = wi_per_group / warp_size.max(1.0);
        let rr = wi_peak_reg_bytes / max_register_bytes.max(1.0);

        let features: [f64; 152] = [
            lng,
            lwpg,
            lops,
            lcop,
            lgmem,
            barr,
            wr,
            rr,
            num_groups * wi_per_group,
            wi_ops / wi_compute_ops.max(1.0),
            ci,
            (wi_compute_ops / (wi_global_load_bits + wi_global_store_bits).max(1.0)).ln_1p(),
            (wi_ops / wi_compute_ops.max(1.0)).ln_1p(),
            ((wi_global_load_bits + wi_global_store_bits) / (num_groups * wi_per_group).max(1.0)).ln_1p(),
            ((wi_local_load_bits + wi_local_store_bits + 1.0) / (wi_global_load_bits + wi_global_store_bits + 1.0).max(1.0)).ln_1p(),
            (wi_ops + 100.0).ln(),
            (wi_ops + 10.0).ln(),
            (wi_compute_ops + 100.0).ln(),
            (1000.0 / wi_ops.max(1.0)).ln_1p(),
            (100.0 / wi_ops.max(1.0)).ln_1p(),
            (1000.0 / wi_compute_ops.max(1.0)).ln_1p(),
            wi_ops / (num_groups * wi_per_group).max(1.0),
            wi_compute_ops / (num_groups * wi_per_group).max(1.0),
            wi_ops / num_groups.max(1.0),
            lwpg.max(1e-8).ln(),
            num_groups,
            num_groups * wi_per_group,
            wi_branches.ln_1p(),
            barr * wi_branches.ln_1p(),
            lwpg * wi_branches.ln_1p(),
            lng * lwpg,
            lwpg * lops,
            (wi_ops / num_groups.max(1.0) + 1.0).ln(),
            (wi_ops / (num_groups * wi_per_group).max(1.0)).ln_1p(),
            1.0 / (num_groups * wi_per_group).max(1.0),
            (1.0 / (num_groups * wi_per_group).max(1.0)).ln_1p(),
            (wi_ops / (num_groups * wi_per_group * wi_barriers.max(1.0)).max(1.0)).ln_1p(),
            (wi_per_group * wi_barriers).ln_1p(),
            (if wi_barriers == 0.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 3.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 4.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 5.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 6.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 7.0 { 1.0 } else { 0.0 }),
            (if wi_barriers == 8.0 { 1.0 } else { 0.0 }),
            if wi_barriers == 0.0 { 1.0 } else { 0.0 },
            if wi_barriers >= 3.0 && wi_barriers <= 5.0 { 1.0 } else { 0.0 },
            if wi_barriers >= 6.0 { 1.0 } else { 0.0 },
            if wi_barriers > 0.0 { 1.0 } else { 0.0 },
            (if wi_barriers == 0.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 0.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 0.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 3.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 3.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 3.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 4.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 4.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 4.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 5.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 5.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 5.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 6.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 6.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 6.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 7.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 7.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 7.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers == 8.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers == 8.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers == 8.0 { 1.0 } else { 0.0 }) * lops,
            barr * lops,
            barr * lcop,
            barr * lgmem,
            barr * lwpg,
            barr * lng,
            barr * wr,
            wi_global_load_lidx_stride.ln_1p(),
            wi_global_store_lidx_stride.ln_1p(),
            wi_global_load_lidx_stride.ln_1p() * lops,
            wi_global_load_lidx_stride.ln_1p() * lcop,
            wi_global_load_lidx_stride.ln_1p() * lgmem,
            lops * lgmem,
            lcop * lgmem,
            lng * lgmem,
            lwpg * lgmem,
            lops * ci,
            lcop * ci,
            lng * ci,
            lng * wr,
            lwpg * wr,
            lng * rr,
            lwpg * rr,
            lng * lcop,
            lwpg * lops,
            wr,
            (32.0 / wi_per_group.max(1.0)).ln(),
            lng * (32.0 / wi_per_group.max(1.0)).ln(),
            lwpg * (32.0 / wi_per_group.max(1.0)).ln(),
            1.0 - (wi_global_load_lidx_stride / 32.0).min(1.0),
            1.0 - (wi_global_store_lidx_stride / 32.0).min(1.0),
            barr / (wi_per_group + 1.0).log2().max(1.0),
            wi_compute_ops / num_groups.max(1.0),
            (32.0 / wi_per_group.max(1.0)).max(1e-8).ln(),
            ((num_groups * wi_per_group) / 2048.0).min(1.0),
            if wi_barriers > 0.0 { (wi_barriers + 1.0).log2() } else { 0.0 },
            barr * (wi_local_load_bits + wi_local_store_bits).ln_1p(),
            wi_compute_ops / (num_groups * wi_per_group).max(1.0),
            (wi_local_load_bits + wi_local_store_bits) / 65536.0,
            wr,
            (32.0 - wi_per_group) / 32.0,
            wi_compute_ops / (num_groups * wi_barriers.max(1.0)).max(1.0),
            barr * (barr).ln_1p() / (wi_ops).ln_1p().max(1.0),
            wi_ops / (num_groups * (wi_per_group).ln_1p()).max(1.0),
            wi_ops / wi_barriers.max(1.0),
            barr / (wi_ops).ln_1p().max(1.0),
            barr / (wi_ops).ln_1p().max(1.0),
            ((wi_global_load_bits + wi_global_store_bits) / wi_compute_ops.max(1.0) + 1.0).ln(),
            (lng.abs()).ln_1p(),
            (lwpg.abs()).ln_1p(),
            (lops.abs()).ln_1p(),
            (num_groups / wi_ops.max(1.0) + 1.0).ln(),
            ((num_groups * wi_per_group) / wi_ops.max(1.0) + 1.0).ln(),
            (if wi_barriers >= 3.0 && wi_barriers <= 5.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lgmem,
            wi_compute_ops / (num_groups * wi_per_group).max(1.0),
            (wi_compute_ops + 1.0).ln() * ((num_groups * wi_per_group) + 1.0).ln(),
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lng,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lwpg,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lops,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lcop,
            (if wi_barriers > 0.0 { 1.0 } else { 0.0 }) * lgmem,
            wi_register_load_bits.ln_1p(),
            wi_register_store_bits.ln_1p(),
            wi_register_load_bits / (wi_global_load_bits + wi_global_store_bits).max(1.0),
            gws0.ln_1p(),
            gws1.ln_1p(),
            gws2.ln_1p(),
            lws0.ln_1p(),
            lws1.ln_1p(),
            lws2.ln_1p(),
            lws0 / wi_per_group.max(1.0),
            lws1 / wi_per_group.max(1.0),
            lws2 / wi_per_group.max(1.0),
            lws0 * lws1,
            gws0 / num_groups.max(1.0),
            gws1 / num_groups.max(1.0),
            max_loop_depth,
            max_loop_depth * lops,
            max_loop_depth * barr,
            local_mem_size.ln_1p(),
            preferred_vector_size,
        ];

        const SM: &[f64] = &[
            7.15793760e+00, 2.14564487e+00, 9.64859344e+00, 9.32425481e+00, 1.12520003e+01, 3.01453237e-01, 1.17459632e+00, 1.90104762e+00,
            3.20598629e+06, 1.40502764e+00, 1.66010276e-01, 1.50061691e-01, 8.72000671e-01, 3.57936835e+00, 1.61430014e-02, 9.77270604e+00,
            9.67100457e+00, 9.48811998e+00, 4.24578279e-01, 1.24112602e-01, 5.14492549e-01, 1.21865422e+06, 8.37790661e+05, 1.22124636e+06,
            4.90562675e-01, 1.96700766e+05, 3.20598629e+06, 1.07666886e-01, 5.46229014e-01, 3.73768289e-01, 1.42926318e+01, 1.94420841e+01,
            3.62832291e+00, 2.56095090e+00, 1.49798201e-02, 1.23955918e-02, 2.53017790e+00, 3.03281871e-01, 9.38261455e-01, 9.21486765e-03,
            2.11952634e-02, 1.25997032e-02, 9.11876822e-03, 5.56308928e-03, 4.04685381e-03, 9.38261455e-01, 4.30098342e-02, 1.87287113e-02,
            6.17385455e-02, 6.71941956e+00, 1.93554743e+00, 9.20151461e+00, 6.99720884e-02, 2.32419234e-02, 6.99342580e-02, 1.88655081e-01,
            7.03255375e-02, 1.47343920e-01, 6.99097827e-02, 4.17566921e-02, 9.87633154e-02, 4.31197058e-02, 3.18838420e-02, 6.83974365e-02,
            3.84090886e-02, 2.32224891e-02, 3.66458003e-02, 2.84522887e-02, 1.96669504e-02, 2.59941021e-02, 2.16785307e+00, 2.01728230e+00,
            2.54463337e+00, 1.07100746e+00, 2.06928567e+00, 4.49457038e-01, 1.86875074e+00, 1.26670667e+00, 1.87414972e+01, 1.81489135e+01,
            2.18477150e+01, 1.15680975e+02, 1.12241115e+02, 7.83796193e+01, 2.28158845e+01, 1.69461825e+00, 1.65016169e+00, 1.22453721e+00,
            7.58830061e+00, 6.11903991e+00, 1.23926932e+01, 3.49351077e+00, 6.47594264e+01, 1.94420841e+01, 1.17459632e+00, 1.64430856e+00,
            1.30725113e+01, 7.47836874e-01, 7.73682904e-01, 8.73617903e-01, 6.25221843e-02, 8.39765863e+05, 1.64430856e+00, 7.17824131e-01,
            1.55330483e-01, 1.88131316e+00, 8.37790661e+05, 4.69204220e-04, 1.17459632e+00, -1.74596316e-01, 8.39668339e+05, 8.01373618e-02,
            1.22015987e+06, 1.44224228e+06, 4.40442903e-02, 4.40442903e-02, 2.07729570e+00, 1.96353363e+00, 1.03292371e+00, 2.32529485e+00,
            1.13766706e+00, 1.89172239e+00, 3.16041494e-01, 4.47078833e-01, 5.25460175e-01, 8.37790661e+05, 8.04237054e+01, 4.38518036e-01,
            2.10097434e-01, 4.47078833e-01, 4.16246936e-01, 5.25460175e-01, 9.82196580e+00, 9.82196580e+00, 4.94035880e-01, 3.77097669e+00,
            3.38528245e+00, 9.74465239e-01, 1.46498209e+00, 1.19559418e+00, 8.11569956e-01, 7.24821730e-01, 6.00224856e-01, 4.71583286e-01,
            2.92994779e+01, 2.79507163e-01, 1.25759357e-01, 1.25421503e+00, 1.29690353e+01, 4.26425208e-01, 1.08026932e+01, 1.60000000e+01,
        ];
        const SC: &[f64] = &[
            3.63002713e+00, 1.54498877e+00, 2.70086682e+00, 2.78964259e+00, 2.66411868e+00, 1.22720912e+00, 3.46566003e+00, 2.30315390e+00,
            4.94640872e+07, 2.64632766e-01, 1.05530948e-01, 8.11085362e-02, 1.03438484e-01, 3.50396082e+00, 1.05135288e-01, 2.46271113e+00,
            2.65243623e+00, 2.48539601e+00, 8.98417099e-01, 3.62168687e-01, 1.03475143e+00, 3.37493812e+07, 2.18302146e+07, 3.37492994e+07,
            7.53699146e-01, 1.91307905e+06, 4.94640872e+07, 4.23781213e-01, 2.32869841e+00, 1.54646199e+00, 1.29512432e+01, 1.42987183e+01,
            3.42740416e+00, 2.99038333e+00, 8.85009701e-02, 6.33232076e-02, 2.97808481e+00, 1.21121473e+00, 2.40680073e-01, 9.55507921e-02,
            1.44034802e-01, 1.11539009e-01, 9.50558588e-02, 7.43783659e-02, 6.34860361e-02, 2.40680073e-01, 2.02879246e-01, 1.35565286e-01,
            2.40680073e-01, 3.79957994e+00, 1.57675838e+00, 3.50954561e+00, 8.58278023e-01, 2.42924714e-01, 7.41565805e-01, 1.47721870e+00,
            4.91957507e-01, 1.02129428e+00, 8.41766358e-01, 3.82109693e-01, 9.01530596e-01, 6.72862742e-01, 3.32363529e-01, 7.30904534e-01,
            6.31125260e-01, 3.10484104e-01, 4.99195111e-01, 5.45703363e-01, 3.08530226e-01, 4.16013255e-01, 8.98269732e+00, 8.39424550e+00,
            1.05019869e+01, 4.68129889e+00, 1.05251487e+01, 2.68450103e+00, 2.23955949e+00, 1.59535416e+00, 2.32381993e+01, 2.24548826e+01,
            2.69707114e+01, 5.28376542e+01, 5.28756400e+01, 4.37591179e+01, 1.63130694e+01, 1.52262126e+00, 1.52566881e+00, 1.05248012e+00,
            2.48565143e+01, 2.25870448e+01, 1.48959106e+01, 5.30416288e+00, 3.89034462e+01, 1.42987183e+01, 3.46566003e+00, 1.80591672e+00,
            1.64509423e+01, 4.35747089e+00, 3.38464687e-01, 2.41490854e-01, 2.50178663e-01, 2.18301532e+07, 1.80591672e+00, 4.09975317e-01,
            6.11387054e-01, 7.73455746e+00, 2.18302146e+07, 1.87974769e-03, 3.46566003e+00, 3.46566003e+00, 2.18301569e+07, 3.55636532e-01,
            3.37493327e+07, 3.38102480e+07, 1.85620894e-01, 1.85620894e-01, 4.03479988e-01, 5.83858163e-01, 4.69960673e-01, 3.02905104e-01,
            2.18534580e+00, 3.12733152e+00, 1.53042225e+00, 1.79035640e+00, 2.09683835e+00, 2.18302146e+07, 3.86352097e+01, 2.15254793e+00,
            8.45062381e-01, 1.79035640e+00, 1.67517373e+00, 2.09683835e+00, 3.70191063e+00, 3.70191063e+00, 4.87888656e-01, 2.07950087e+00,
            2.20899857e+00, 1.00496967e+00, 1.08614435e+00, 9.39616929e-01, 5.59244732e-01, 4.05902765e-01, 4.37737489e-01, 4.37985457e-01,
            8.97869462e+01, 4.19281168e-01, 2.50786999e-01, 7.68756393e-01, 9.41742940e+00, 1.96406236e+00, 1.00000000e+00, 1.00000000e+00,
        ];
        const RC: &[f64] = &[
            -5.15543277e-02, -2.06968955e+00, 2.48654548e+00, -3.63763329e+01, 2.74527274e+01, -3.71455180e-02, 3.60183432e-01, 1.24308204e-01,
            1.48896349e-03, 2.27933670e-01, 5.61815916e-01, 2.11819154e-01, -8.42195569e-01, -1.48556235e-01, 2.07674718e-02, 2.62890184e+00,
            1.74792940e-01, 7.91134134e-01, -3.23793509e-01, -6.67129738e-01, 3.43536536e-01, -4.24230545e+00, -3.14164908e+00, -1.22120917e+01,
            -2.13919632e+00, -5.57341575e-03, 1.48924376e-03, -4.54729373e-02, -2.97016277e-02, -1.49526664e-01, 7.42384647e-01, 3.39395808e-01,
            1.45347419e+00, -4.17992430e-01, -1.60978349e-01, 2.09362464e-01, 4.66654057e-01, -1.38334998e-01, 5.15890635e-02, -3.84310359e-02,
            -4.44290038e-02, -1.42561360e-02, -2.55975278e-02, -2.08031459e-03, 2.88671600e-02, 5.15890206e-02, -5.74828716e-02, -5.56937867e-03,
            -5.15891073e-02, -4.30408092e-02, -1.93630956e+00, 1.79742318e+00, -4.71302458e-03, -1.08319632e-01, 1.66457297e-01, -5.04265084e-03,
            -1.67124130e-01, 1.52027015e-01, -3.81874351e-03, -9.36317193e-02, 7.10204244e-02, -7.23314594e-03, -2.55980502e-02, 8.89471342e-02,
            -4.00748275e-03, -2.07902926e-03, 2.39966727e-02, -2.75187498e-03, 2.88681693e-02, -2.88876492e-02, 1.88060370e-01, 2.88958363e-01,
            3.74898328e-02, -1.21978576e-01, -1.11085567e-02, -4.98187559e-02, -7.52174656e-02, -4.12358241e-02, -1.66845219e+00, 8.37140163e-01,
            8.98333929e-01, 4.37567991e+00, -4.89868812e+00, 4.23150823e-01, 3.51485779e-02, -1.17039616e+00, 1.01476280e+00, 3.07143983e-02,
            -2.64419503e-02, -1.03949897e+00, -8.21646427e-02, -3.28015370e-03, 1.50113211e+00, 3.39395877e-01, 3.60183383e-01, -4.55418678e+00,
            8.84295011e-01, 1.12939216e+00, -3.46533035e-02, -1.42409926e-02, 1.50757392e-01, -1.58297962e+01, -4.55418678e+00, 3.11964587e-03,
            -4.54704882e-02, -5.03862486e-02, -3.14164837e+00, -1.30326642e-01, 3.60183373e-01, -3.60183523e-01, 2.52295053e+01, -3.97294318e-01,
            1.62371265e+01, 2.31202681e-01, 1.96931842e-01, 1.96931842e-01, -4.27571654e+00, -6.73311036e-02, -2.21774325e+00, -1.06762873e+00,
            -8.79192042e-01, 2.28834025e-02, 2.23947823e-01, 2.27719623e-01, -1.90682939e-02, -3.14164837e+00, -1.93077320e+00, -1.09719546e-02,
            -1.71064976e-01, 2.27719620e-01, -2.48849525e-01, -1.90683688e-02, 8.47157029e-03, 8.47152888e-03, 4.67585101e-03, 5.17726382e-01,
            5.50291491e-01, 2.94500819e-01, -5.60204283e-02, -9.90789454e-02, -5.46994557e-02, 4.01484031e-02, 9.48052448e-02, 2.74520610e-02,
            -1.02195405e-02, -2.74368391e-02, -3.89449591e-03, 7.92983390e-03, -2.32795746e-02, -4.03727682e-03, -1.14972971e-26, 0.00000000e+00,
        ];
        let ri: f64 = 5.00000000e-01;

        let mut pred = ri;
        for i in 0..152 {
            pred += RC[i] * (features[i] - SM[i]) / SC[i];
        }
        pred * 1_000_000.0
    }
}
