[package]
name = "zyx"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generic tensor library and extensions."
homepage = "https://github.com/zk4x/zyx"
repository = "https://github.com/zk4x/zyx"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.5.3"
duplicate = "0.4.1"

# optional dependencies
matrixmultiply = { version = "0.3.2", features = ["threading"], optional = true }
cblas-sys = { version = "0.1.4", optional = true }
blas-src = { version = "0.8", features = ["blis"], optional = true }

[features]
matrixmultiply = ["dep:matrixmultiply"]
cblas = ["dep:cblas-sys", "dep:blas-src"]
