[package]
name = "zyx"
version = "0.11.0"
authors = ["zk4x"]
edition = "2021"
description = "Machine learning tensor library"
documentation = "https://docs.rs/zyx"
readme = "README.md"
homepage = "https://github.com/zk4x/zyx"
repository = "https://github.com/zk4x/zyx"
license = "MIT OR Apache-2.0"
keywords = ["tensor", "generic", "deep-learning", "neural-network", "autodiff"]
categories = ["computer-vision", "science"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
matrixmultiply = { version = "0.3.8", default-features = false, features = ["threading"], optional = true }
rayon = { version = "1.8.0", default-features = false, optional = true }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"], optional = true }
cl3 = { version = "0.9.2", default-features = false, features = ["CL_VERSION_1_2"], optional = true }

[features]
default = ["cpu", "opencl", "rand", "io", "debug1"]
cpu = ["matrixmultiply", "rayon"]
opencl = ["dep:cl3"]
rand = ["dep:rand"]
io = [] # io requires std
debug1 = [] # debug requires std

[profile.release]
opt-level = 3 #"z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true
overflow-checks = false
debug = 0
