[package]
name = "zyx"
version = "0.9.0"
authors = ["zk4x"]
edition = "2021"
description = "Generic tensor library and extensions."
documentation = "https://docs.rs/zyx"
readme = "README.md"
homepage = "https://github.com/zk4x/zyx"
repository = "https://github.com/zk4x/zyx"
license = "MIT OR Apache-2.0"
keywords = ["tensor", "generic", "deep-learning", "neural-network", "autodiff"]
categories = ["computer-vision", "science", "simulation", "text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duplicate = { version = "0.4.*" }
rand = { version = "0.8.*" }
rayon = { version = "1.*" }

# optional dependencies
matrixmultiply = { version = "0.3.*", features = ["threading"], optional = true }
#ndarray = { version = "0.15.*", features = ["rayon", "matrixmultiply-threading"], optional = true }
#num-traits = { version = "0.2.*", optional = true }

[features]
matrixmultiply = ["dep:matrixmultiply"]
#ndarray = ["dep:ndarray", "dep:num-traits"]
