[workspace]
resolver = "2"
members = [
  "zyx-core",
  "zyx-cpu",
  "zyx-torch",
  "zyx-nn",
  "zyx-opencl",
  "zyx-test",
  "zyx-optim",
  "zyx",
  "zyx-derive",
  "zyx-examples",
  "zyx-compiler",
]

[workspace.dependencies]
zyx-core = { path = "./zyx-core", version = "0.1.0", default-features = false }
zyx-compiler = { path = "./zyx-compiler", version = "0.1.0", default-features = false }
zyx-opencl = { path = "./zyx-opencl", version = "0.1.0" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true
overflow-checks = false
debug = 0
