[package]
name = "zyx"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generic tensor library and extensions."
homepage = "https://github.com/zk4x/zyx"
repository = "https://github.com/zk4x/zyx"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.5.3"
duplicate = "0.4.1"
