[workspace]
resolver = "2"

members = [
  "zyx-core", "zyx-cpu", "zyx-torch", "zyx-nn", "zyx-opencl", "zyx-test", "zyx-optim", "zyx",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true
overflow-checks = false
debug = 0
