[package]
name = "zyx"
version = "0.11.2"
authors = ["zk4x"]
edition = "2021"
description = "Machine learning tensor library"
documentation = "https://docs.rs/zyx"
readme = "README.md"
homepage = "https://github.com/zk4x/zyx"
repository = "https://github.com/zk4x/zyx"
license = "MIT OR Apache-2.0"
keywords = ["tensor", "generic", "deep-learning", "neural-network", "autodiff"]
categories = ["computer-vision", "science"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
rclite = { version = "0.2.4", default-features = false }
libm = { version = "0.2.7", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
gemm = { version = "0.15.4", default-features = false, optional = true }
rayon = { version = "1.8.0", default-features = false, optional = true }
cl3 = { version = "0.9.2", default-features = false, optional = true }

[features]
#default = ["cpu", "opencl", "io", "debug1"]
#default = ["cpu", "opencl"]
cpu = ["gemm", "rayon"]
opencl = ["dep:cl3"]
io = [] # io requires std
debug1 = [] # debug requires std

[profile.release]
opt-level = 3 #"z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true
overflow-checks = false
debug = 0
