[workspace]
resolver = "2"
members = [
  "zyx-core",
  "zyx-cpu",
  "zyx-torch",
  "zyx-nn",
  "zyx-opencl",
  "zyx-test",
  "zyx-optim",
  "zyx",
  "zyx-derive",
  "zyx-examples",
  "zyx-compiler",
]

[workspace.package]
version = "0.1.1"
edition = "2021"

[workspace.dependencies]
zyx-core = { version = "0.1.1", path = "./zyx-core", default-features = false }
zyx-compiler = { version = "0.1.1", path = "./zyx-compiler", default-features = false }
zyx-opencl = { version = "0.1.1", path = "./zyx-opencl", default-features = false }
zyx-cpu = { version = "0.1.1", path = "./zyx-cpu", default-features = false }
zyx-torch = { version = "0.1.1", path = "./zyx-torch", default-features = false }
zyx-nn = { version = "0.1.1", path = "./zyx-nn", default-features = false }
zyx-optim = { version = "0.1.1", path = "./zyx-optim", default-features = false }
zyx-derive = { version = "0.1.1", path = "./zyx-derive", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
strip = true
overflow-checks = false
debug = 0
