[workspace]
resolver = "2"
members = [
    "mnist",
    "mnist-snn",
    "nanogpt",
    "phi",
    "readme-test",
    "rnn",
    "tiny-net",
    "tiny-net2",
    "llama",
    "probe",
    "qwen3.8-27b",
]

[profile.release]
opt-level = 1
strip = false
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 16
debug = true
