[package]
name = "zyx-opencl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zyx-core = { version = "*", path = "../zyx-core" }
cl3 = { version = "0.9.5", default-features = false }
